version: 2.1

workflows:
  build_and_test:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build

jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            bash scripts/cp-env-to-properties.sh
            bash scripts/install-dependencies.sh
      - run:
          name: Build
          command: ./gradlew assemble -PdisablePreDex --stacktrace --no-daemon -x androidJavadocs
  deploy:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            bash scripts/cp-env-to-properties.sh
            bash scripts/install-dependencies.sh
      - run:
          name: Deploy
          command: bash scripts/deploy.sh
